### PR TITLE
Proximity-based server selection

### PR DESCRIPTION
**Pull request by atavism**

### CODE REVIEW

**Comment by myleshorton** [comment]
Thanks on this @atavism! I think this is a great area for us to really nail down, and a couple of thoughts come to mind.

First, I think we should probably use nginx for our proxies in general, although I would be curious to dig more into it versus mod_proxy, squid, etc. So as a completely separate issue, that's a change I would support simply based on it:

1. Providing better blocking resistance for the reasons you mentioned
1. Being much better battle tested at scale than anything we're running

In terms of the LEP proper, the thing that's the most unclear to me here is the initial setup. I.e., I understand how the GeoIP module is handy for web pages where you basically redirect the request to index.html so that all subsequent links are loaded via the geolocated server (assuming each server has separate links in its index.html to server files from itself). For us, though, our requests aren't dependent on each other like that. So we'd make some initial request for something we need early on and would then just use whatever server we were redirected to from that point moving forward, something like that?

I did think @xiam's idea of integrating this logic into our geoserver is interesting since that server already knows your location, but the redundancy of having that logic run on every proxy is also nice. We could also integrate some custom header into that response that included the users geo information, which would obviate the need for our own geo-ip server tool.

We'd also want to run their GeoIP DB download via cron each week just to keep it up to date (I believe Maxmind releases updates every Tue to that database):

```
wget -N http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
gunzip GeoLiteCity.dat.gz
mv GeoLiteCity.dat /usr/share/GeoIP/
```

That's sort of a random smattering of thoughts, but loosely I'm increasingly on board with this approach. What do you guys think @xiam, @aranhoide, and @fffw?

**Comment by fffw** [comment]
Maybe I missed some context and lack of some basic knowledge, but just a few random thoughts.

1. Clients can request geo info from geoserver and save it to lantern.yaml. Since they can determine which subdomain to reach by themselves, in which circumstance they'll reach non-optimised servers and need a redirect?

In terms of block resistance, the location-based subdomains still need DNS lookup and hence can be blocked. Will we resolve an IP address for client at the server side?

Is it related to [always use direct proxies](https://github.com/getlantern/lantern/issues/2321)?

2. What about peers not in server pools? How can they get chose geographically?

3. So many server nodes which keep data synced and redirect to each other seems harder to maintain and less predictable than a single service (geoserver I mean), though it's more P2P. As accessing to geoserver is proxied, and the result is persisted locally, and accessing a slow server just degrades but not disables the functionality, a temporary outage of geoserver might not affect too much.

**Comment by myleshorton** [comment]
Thanks @fffw! Some excellent thoughts and questions. Responses below.

> Clients can request geo info from geoserver and save it to lantern.yaml. Since they can determine which subdomain to reach by themselves, in which circumstance they'll reach non-optimised servers and need a redirect?

Part of the thought here is just to move as much logic as possible to the server side so we can globally control things. So this could theoretically make the geoserver while also removing any logic from the client in terms of what data center to go to.

> In terms of block resistance, the location-based subdomains still need DNS lookup and hence can be blocked. Will we resolve an IP address for client at the server side?

Yeah we'd probably use IP addresses and not domains. 

> Is it related to always use direct proxies?

Yeah this would only be for direct proxies. We still need flashlight for domain fronted proxies for sure.

> What about peers not in server pools? How can they get chose geographically?

Yeah I think we need to start adding peers in give mode to geo-specific server pools actually. I think that'll be an important change.

> So many server nodes which keep data synced and redirect to each other seems harder to maintain and less predictable than a single service (geoserver I mean)

Yeah that's an interesting point. They would all be deployed with salt, though, so theoretically keeping the configs synced up should not be a big deal. This would just build that functionality in fairly seamlessly to every server we run, so would offer some redundancy.

**Comment by aranhoide** [comment]
Not to rain on your parade, but it just came to mind that
- I think the ultimate goal in this topic is that the client itself selects a server based on actual measurements of speed to several ones. 
- I think our drive to do things on the server side in the interim is caused by our having more control over the servers than over the clients, but that stops being true once we have auto-updates.

So does it really make sense to configure a server at all?

**Pull request closed without merging**
